# Form implementation generated from reading ui file '/Users/elyor/Documents/qt-projects/picture-searcher/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("font: 14pt;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 120, 311, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.searchDir = QtWidgets.QLineEdit(parent=self.widget)
        self.searchDir.setObjectName("searchDir")
        self.horizontalLayout.addWidget(self.searchDir)
        self.browseBtn = QtWidgets.QToolButton(parent=self.widget)
        self.browseBtn.setObjectName("browseBtn")
        self.horizontalLayout.addWidget(self.browseBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchBtn = QtWidgets.QPushButton(parent=self.widget)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout_2.addWidget(self.searchBtn)
        self.stopBtn = QtWidgets.QPushButton(parent=self.widget)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_2.addWidget(self.stopBtn)
        self.showBtn = QtWidgets.QPushButton(parent=self.widget)
        self.showBtn.setObjectName("showBtn")
        self.horizontalLayout_2.addWidget(self.showBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Picture Searcher"))
        self.label.setText(_translate("MainWindow", "Search directory:"))
        self.browseBtn.setText(_translate("MainWindow", "..."))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.showBtn.setText(_translate("MainWindow", "Show"))
